### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by edib-isic** [skinny-framework/skinny-framework-example#1]
This is not compiling after running skinny run i get following errors

./skinny run
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\Users\edibi\Documents\GitHub\skinny-framework-example\project
[info] Loading settings from build.sbt ...
[info] Set current project to skinny-blank-app-dev (in build file:/C:/Users/edibi/Documents/GitHub/skinny-framework-example/)
[info] Compiling 12 Scala sources to C:\Users\edibi\Documents\GitHub\skinny-framework-example\target\dev\scala-2.13.0-M4\classes ...
[warn] C:\Users\edibi\Documents\GitHub\skinny-framework-example\src\main\scala\Bootstrap.scala:19:51: procedure syntax is deprecated: instead, add `: Unit =` to explicitly declare `initSkinnyApp`'s return type
[warn]   override def initSkinnyApp(ctx: ServletContext) {
[warn]                                                   ^
[error] C:\Users\edibi\Documents\GitHub\skinny-framework-example\src\main\scala\model\Company.scala:17:95: macro implementation not found: apply
[error] (the most common reason for that is that you cannot use macro implementations in the same compilation run that defines them)
1. Waiting for source changes... (press enter to interrupt)
[error]   override def extract(rs: WrappedResultSet, rn: ResultName[Company]): Company = autoConstruct(rs, rn)
[error]                                                                                               ^
[warn] one warning found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 9 s, completed 23.04.2019, 14:24:23

Can you help me out with this?

**Comment by seratch** [comment]
We don't support scala-2.13.0-M4. Please try it out with a stable Scala version like 2.12.8.

**Comment by seratch** [comment]
The latest version supports 2.13.0.
